name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Build and save the Docker image
      run: |
        docker build --tag ndi-recorder-ci:$(date -I) .
        docker image save --output ndi-recorder.tar ndi-recorder-ci:$(date -I) 
    - name: Archive the Docker image
      uses: actions/upload-artifact@v4
      with:
        name: ndi-recorder-image-archive
        path: ndi-recorder.tar
        retention-days: 30
